### ISSUE TITLE
Fails for dotnet5

### ISSUE THREAD

**Issue by codingyourlife** [huysentruitw/entity-framework-core3-mock#5]
Will there be a new package or is there a new one? Could you mention this in the readme maybe?

**Comment by huysentruitw** [comment]
The code in this repository is specifically targeting EF Core 3, as stated in the README.
The idea is to drop my repository with EF Core 2 support in favor of EF Core 5, see also https://github.com/huysentruitw/entity-framework-core3-mock/pull/4#issuecomment-725527781

I'll try to do this transformation within a day or 3.

**Comment by huysentruitw** [comment]
Please visit my other repository for EF Core5 support: https://github.com/huysentruitw/entity-framework-core-mock

Essentially everything stays the same, just remove the '3' from the NuGet package names and pull them in.
