### ISSUE TITLE
Support for .Net Framework 4.8

### ISSUE THREAD

**Issue by duhowise** [huysentruitw/entity-framework-core3-mock#6]
My team uses EntityFrameworkCore 3.1.12 which supports .net 4.8  without any issues.
I see how ever that entity-framework-core3-mock does not support 4.8 and cannot be used.
Is there any way around this?

**Comment by huysentruitw** [comment]
Hi, would you be good if the library targets netstandard2.0?

**Comment by huysentruitw** [comment]
(Note to self: pressing Ctrl+Shift+Enter closes the issue :D )

**Comment by duhowise** [comment]
Just doing some tests locally and seeing that supporting netstandard 2.0 might not be the solution
I have upgraded my fork to the latest efcore version to run some tests

**Comment by huysentruitw** [comment]
Version 1.0.0.9 has just been pushed to NuGet that should fix this issue. Please test and report back. Thank you.

Note: it can take a few minutes before the package shows up in NuGet.
