### ISSUE TITLE
Could not find a constructor that would match given arguments

### ISSUE THREAD

**Issue by huysentruitw** [huysentruitw/entity-framework-core3-mock#8]
Can we discus the new issue you're having here @duhowise ?

Link to comment:
https://github.com/huysentruitw/entity-framework-core3-mock/pull/7#issuecomment-783440868

> Update:
> 
> ```
>  var options = new DbContextOptionsBuilder<CoreERPDB>()
>                 .UseInMemoryDatabase(Guid.NewGuid().ToString())
>                 .EnableSensitiveDataLogging();
> 
>      var       mockCoreERPDB = new DbContextMock<CoreERPDB>(options);
> ```
> 
> fails with error message:
> 
> ```
>  Message: 
>     Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: CoreERPDB
>     Could not find a constructor that would match given arguments:
>     Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.EntityFrameworkCore.DbContext]
> ```
>

**Comment by huysentruitw** [comment]
@duhowise, can you show which constructors the `CoreERPDB` class has? Probably, there's either no argument or more than one. The arguments you pass to `new DbContextMock<CoreERPDB>(<arguments>)` must reflect what your constructor needs.

**Comment by huysentruitw** [comment]
Seems like this is already resolved: see https://github.com/huysentruitw/entity-framework-core3-mock/pull/7#issuecomment-783549685

**Comment by duhowise** [comment]
> 
> 
> @duhowise, can you show which constructors the `CoreERPDB` class has? Probably, there's either no argument or more than one. The arguments you pass to `new DbContextMock<CoreERPDB>(<arguments>)` must reflect what your constructor needs.

We can however discuss this further for scenarios where you're not allowed to modify the existing dbcontext for your tests...

**Comment by huysentruitw** [comment]
I think it's because 'var options' is still the builder instance as your code is lacking the `.Options`.

Also, you don't need to call inmemorydatabase etc, you just need a dummy options object of the correct generic type.

In your case, I'd try this:

```csharp
var options = new DbContextOptionsBuild<CoreERPDB>().Options;
```

**Comment by duhowise** [comment]
Very well I'll test and get back to you

**Comment by duhowise** [comment]
Your suggestion worked. I'll share more details as soon as I can

**Comment by duhowise** [comment]
> 
> 
> Your suggestion worked. I'll share more details as soon as I can

```
public DbContextOptions<CoreERPDB> Options { get; } = new DbContextOptionsBuilder<CoreERPDB>().Options;

```
with this I get to keep the original constructor and have the mocking to instantiate the dbcontext without any issues

**Comment by huysentruitw** [comment]
That's good news. Thanks for the update!
